#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [a4paper]
#+LATEX_HEADER: \usepackage{xyz}

* Chapter 1
** The key to minimizing risk in large projects is to find a way to "slice the ele-phant"
   that is, find a way to release the system in small increments instead
   of saving up for a big-bang release at the end. Ideally, each increment should
   independently add value to the users and knowledge to the teams.
* Chapter 2: Teams
** Team up
   create teams for development, testing, analyzing and etc
** Teams should not be separated.
   Each team should have some people embeded from other teams with different goal.
   For example Delta development team should have a person from analyzing and one from
   testing team.
* Chapter 3: Parties
** Project Sync
*** Teams gathered up in mornings and talked about their tasks. (development groups)
*** An other gathering for field specific teams like testing team, analyze team, and development leaders
*** Leaders and developers gather in front of main project board and talk about the "big picture"
    to find out what does each team do today, what does block us, what did we need and etc

    One of the tasks of this meetup is to easily decide which team do what task ?
    There is no iron rule and it is the key to agile in big projects. Page 17
*** Each meeting is limited to 15 or 20 minutes and meetings are open
    If there were problems that can't be fixed in these short meeting and standup talkings
    members schedule a meeting right after these meetups to fix them

* Chapter 4: Project Board
** Kanban board
   kanban board is board which has a distinct structure and flow.
   It has idea column in left side and In production in right side.
   Each idea or feature specified by cards.
   cards moves from left side of the board to the right side of the board.
   columns are (optional of course):
   - Idea
   - Features
   - Next ten featuers
   - Development
   - System test
   - User acceptance test
   - Production
*** Important and emergency issue handled by labels on issue card
    By putting labels in different color on a card which need an
    emergency care we provide more details about situation like
    blocker or problem  description.

* Chapter 5: Kanban Board
  Each feature in development section of project board will be appear
  in each development team private board. Feature breaks down to tasks
  in team board and each developer work on several. task owners distinct by
  their avatar
* Chapter 6: High Level Goal
** Team members may not have a view of high-level goal or may have a different view.
** It's good to announce high-level goal and its milestone to team by a seperate board in addition to kanban board
** After each release we have to create a new goal statement for next release
** Each week or two, We have to have a reality check
   by asking team members about "Do you believe we’ll reach this goal?", they can give points to this question
*** After each voting we have to discuss about current situation
    If every thing is fine, then how we keep up good work ?
    If not, we have to find solutions like adjusting our goal, changing feature list or any thing else

* Need to google
** TODO epic card
